version: '3.4'

services:
  app:
    image: eccc-on-site-access:development
    build: .
    ports:
      - '4000:4000'
    volumes:
      - .:/usr/src/app
  test:
    depends_on:
      - app
    image: eccc-on-site-access:development
    volumes:
      - .:/usr/src/app
    command: /bin/true
