version: '3.4'

services:
  app:
    image: eccc-on-site-access:development
    env_file:
      - .env
    build: .
    tty: true
    stdin_open: true
    environment:
      NODE_ENV: development
    ports:
      - '4000:4000'
    # lets you test aganst a local verions of PROOF core-app.
    # network_mode: host
    volumes:
      - .:/usr/src/app
  test:
    image: eccc-on-site-access:development
    depends_on:
      - app
    environment:
      NODE_ENV: test
    # Lets you test against a local version of PROOF core-app.
    # network_mode: host
    volumes:
      - .:/usr/src/app
    command: /bin/true
