version: '3.4'

services:
  app:
    image: eccc-on-site-access:development
    build: .
    tty: true
    stdin_open: true
    ports:
      - '4000:4000'
    volumes:
      - .:/usr/src/app
  test:
    image: eccc-on-site-access:development
    depends_on:
      - app
    volumes:
      - .:/usr/src/app
    command: /bin/true
