version: '3.4'

services:
  app:
    env_file:
      - .env
    build: .
    environment:
      NODE_ENV: production
    # ports:
    #   - '4000:4000'
    labels:
      - 'traefik.enable=true'
      - 'traefik.frontend.rule=Host:eccc-on-site-access.proofgov.com'
      - 'traefik.port=4000'

networks:
  default:
    external:
      name: ProofNet
