version: "3.4"

services:
  app:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/usr/src/app
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:eccc-on-site-access.proofgov.com"
      - "traefik.port=4000"
