---
title: Yukon Traveller Form v3
id: 5ebed3975479080101f5eb48
cuid: cka8hjs3h000275ntmrydla3t
created_at: '2020-05-15T17:38:31.037Z'
sections:
- id: 582c9e6c-5fd9-47e1-bc37-16a1b6c3cb02
  label: Traveller's Declaration
  fields:
  - id: 429187d8-51fa-45bc-90a7-00aa940fe9c4
    label: 'I identify as one of the following:'
    binding: traveller.Identifier
    type: multicheck
    choices:
    - label: Resident of the Yukon
      value: '1'
    - label: Non-Resident of the Yukon (Not for transit to Alaska or other parts of
        Canada)
      value: '2'
    - label: Non-Resident of the Yukon (Only for transit to Alaska or other parts
        of Canada)
      value: 3
  - id: 7476dcd4-e049-433b-a55b-2dc0ec90e16c
    label: Name
    binding: traveller.name
    type: text
  - id: c35d1657-0c46-4612-aa31-bc45cd3dacf1
    label: Address of your Residence (where you will be isolating yourself)
    binding: traveller.Address
    type: text
  - id: 624e1b2c-fbdd-44b7-b34f-4b4e9f74b241
    label: Telephone Number (you must be available at this number)
    binding: traveller.telephone
    type: text
  - id: a21c1431-413e-49b7-802d-452d35cca403
    label: Purpose of Entry
    binding: entry.purpose
    type: dropdown
    choices:
    - label: Travel to my place of residence in Yukon
      value: '1'
    - label: Stay with a family member at their place of residence in Yukon
      value: '2'
    - label: Provide critical or essential services in Yukon or in the BC-Yukon border
        area
      value: '3'
    - label: Transit through Yukon as described in subsection 2(3) of the Health Order
      value: '4'
    - label: Engage in activities described in the Traditional Activities Order
      value: '5'
  - id: 3c8b73c3-2065-4f31-b3d5-cb2ae94895f6
    label: Documentation to support your purpose for entering the Yukon
    binding: support.entrydocument
    type: long-text
  - id: 9d8b5185-1860-47e0-8b97-3bdae5a51747
    label: Have you been outside Canada in the last 14 days?
    binding: outside.canada
    type: multicheck
    choices:
    - label: 'Yes'
      value: '1'
    - label: 'No'
      value: '2'
  - id: ac02e24f-a223-4fbc-8805-b4c3fb84a03e
    label: What locations have you visited in the last 14 days?
    binding: locations.visited14days
    type: long-text
  - id: 9d7c5a4b-8056-441d-a6f5-f8cc09ab3b21
    label: Isolation plan/Plan after 14 day isolation complete
    binding: nonresident.nottransitPlan
    type: long-text
  - id: 1ca7c8db-212f-485b-b122-6539c196db30
    label: Plan travelling through Yukon
    binding: nonresident.transitPlan
    type: long-text
  - id: f3de75c3-5e75-4c24-8665-3942acb777b1
    label: This information is true and correct. I am aware that if I am granted entry
      to Yukon, the Chief Medical Officer of Health requires me to self-isolate for
      14 days. If I am defined as an essential service, I must self-isolate for 14
      days. If I am defined as a critical service, I am required to follow the direction
      and guidelines for the delivery of critical services. I am also aware that I
      must act in accordance with this declaration and any enforcement orders or health
      emergency orders related to COVID-19.
    binding: resident.yukonDeclaration
    type: multicheck
    choices:
    - label: Agree
      value: '1'
    - label: Disagree
      value: '2'
  - id: 37c8c52a-4b2b-4d34-a619-1e97b1d38f26
    label: Do you have any COVID-19 symptoms?
    binding: covid.SymptomYesNo
    type: multicheck
    choices:
    - label: I have symptoms
      value: '1'
    - label: No symptoms
      value: '2'
  - id: 5689b9d9-a75b-4995-b91f-e7140812ddf3
    label: What symptoms are you experiencing?
    binding: covid.Symptoms
    type: multicheck
    choices:
    - label: Cough
      value: '1'
    - label: Fever
      value: '2'
    - label: Difficulty breathing
      value: 3
  - id: 2ca34cbc-0275-489b-9356-33500bce8382
    label: This information is true and correct. I am aware that if I am granted entry
      to Yukon, the Chief Medical Officer of Health requires me to self-isolate for
      14 days. If I am defined as an essential service, I must self-isolate for 14
      days. If I am defined as a critical service, I am required to follow the direction
      and guidelines for the delivery of critical services. I am also aware that I
      must act in accordance with this declaration and any enforcement orders or health
      emergency orders related to COVID-19.
    binding: nonresident.nottransitDeclaration
    type: multicheck
    choices:
    - label: Agree
      value: '1'
    - label: Disagree
      value: '2'
  - id: 5e01da96-ce32-4599-b7e9-93b3ea0d1bb7
    label: This information is true and correct. I am aware that the Civil Emergency
      Measures Health Protection Order requires me to complete my transit of Yukon
      within 24 hours of entry. Failure to comply with the Orders is punishable by
      Law.
    binding: nonresident.transitDeclaration
    type: multicheck
    choices:
    - label: Agree
      value: '1'
    - label: Disagree
      value: '2'
- id: 426507eb-26ef-4657-9ae0-8fda515b9b14
  label: Traveller's Declaration
  fields:
  - id: 7b2eee87-0f8d-4384-a983-309d3c6f0729
    label: Point of Entry
    binding: pointofentry.Travel
    type: dropdown
    choices:
    - label: Whitehorse Airport
      value: '1'
    - label: Alaska Hwy
      value: '2'
    - label: Stewart Cassiar Hwy
      value: '3'
    - label: Dempster Hwy
      value: '4'
    - label: Dawson City Airport
      value: '5'
    - label: Watson Lake Airport
      value: '6'
    - label: Mayo Airport
      value: '7'
    - label: Beaver Creek Airport
      value: '8'
    - label: Burwash Landing Airport
      value: '9'
    - label: Carcross Airport
      value: '10'
    - label: Carmacks Airport
      value: '11'
    - label: Faro Airport
      value: '12'
    - label: Haines Junction Airport
      value: '13'
    - label: Old Crow Airport
      value: '14'
    - label: Pelly Crossing Airport
      value: '15'
    - label: Ross River Airport
      value: '16'
    - label: Teslin Airport
      value: '17'
  - id: 8323173b-9f50-4f90-822a-d99c309f09f4
    label: Travel Mode
    binding: officeuse.travelMode
    type: multicheck
    choices:
    - label: Vehicle
      value: '1'
    - label: Flight
      value: '2'
  - id: cf401498-671d-4572-9a01-062a1395997f
    label: License Plate
    binding: officeuser.Licenseplate
    type: text
  - id: e434d84a-6907-4551-80e6-1967a177a055
    label: Airline
    binding: officeuser.Airline
    type: text
  - id: d16a41d4-5247-4907-81fa-b1acf01abfdd
    label: Flight Number/Registration Number
    binding: officeuse.flightNumber
    type: text
  - id: 8a0eb53b-6921-4ced-bc45-abe9035b228d
    label: Date of Entry
    binding: officeuse.Dateentry
    type: date
  - id: b1a1d6ae-a6c1-4bb8-b7dc-b8162cbea9cc
    label: Time of Entry (optional)
    binding: officeuse.Timeentry
    type: text
  - id: 4c02262f-a88d-4503-a20a-5659f9d2c093
    label: Destination
    binding: destionation.structured
    type: dropdown
    choices:
    - label: Whitehorse
      value: '1'
    - label: Beaver Creek
      value: '2'
    - label: Burwash Landing
      value: '3'
    - label: Carcross and Tagish
      value: '4'
    - label: Carmacks
      value: '5'
    - label: Dawson City
      value: '6'
    - label: Faro
      value: '7'
    - label: Haines Junction
      value: '8'
    - label: Mayo
      value: '9'
    - label: Mount Lorne
      value: '10'
    - label: Old Crow
      value: '11'
    - label: Pelly Crossing
      value: '12'
    - label: Ross River
      value: '13'
    - label: Teslin
      value: '14'
    - label: Watson Lake
      value: '15'
    - label: Outside Yukon
      value: '16'
  - id: 287343ca-e11a-4207-8902-497df0f0552f
    label: 'If destination is outside Yukon, please specify where:'
    binding: destination.other
    type: text
  - id: 79172686-6980-4f6c-9a90-00536d072ba9
    label: Identification (provided to verify information on this form)
    binding: officeuse.ID
    type: dropdown
    choices:
    - label: Passport
      value: '1'
    - label: Birth Certificate
      value: '2'
    - label: Driver's License
      value: '3'
    - label: Canadian military identification card
      value: '4'
    - label: Government-issued identification card
      value: '5'
    - label: Canadian citizenship card
      value: '6'
    - label: Status card
      value: '7'
  - id: 5491b0dc-aecc-476d-82f4-c9492a8cbe88
    label: Additional Remarks
    binding: officeuse.additionalRemarks
    type: long-text
